### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by Yepoleb** [Anuken/Koru#11]
I would really like to try this project, but I can't figure out how to build it, because I don't usually write Java code. Please add a simple command list to the Readme with all commands necessary to get the game to run.

**Comment by IanKensey** [comment]
I too am struggling to get to build the code.  Any advice or suggestions would be welcomed.

**Comment by Anuken** [comment]
Added; see [this link](https://github.com/Anuken/Koru#building).

**Comment by Yepoleb** [comment]
Thanks! I don't mind if there are bugs, I just want to see how others have implemented this kind of game before I work on it myself.
