### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by The28AWG** [Anuken/Koru#9]
Hello!

> ../../../../src/intel/isl/isl.c:1370: FINISHME: validate row pitch of stencil surfaces
> Exception in thread "main" java.lang.RuntimeException: Fragment shader:
> 0:15(15): error: no function with name 'textureSize2D'
> 0:19(20): warning: `size' used uninitialized
> 0:19(16): error: could not implicitly convert operands to arithmetic operator
> 0:19(11): error: cannot construct `vec2' from a non-numeric data type
> 0:27(44): warning: `v' used uninitialized
> 0:27(100): warning: `v' used uninitialized
> 0:28(43): warning: `v' used uninitialized
> 0:28(99): warning: `v' used uninitialized
> 
>         at io.anuke.ucore.graphics.Shader.<init>(Shader.java:14)
>         at io.anuke.ucore.core.Shaders.load(Shaders.java:17)
>         at io.anuke.koru.modules.Renderer.loadShaders(Renderer.java:96)
>         at io.anuke.koru.modules.Renderer.<init>(Renderer.java:72)
>         at io.anuke.koru.Koru.init(Koru.java:51)
>         at io.anuke.ucore.modules.ModuleController.create(ModuleController.java:98)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:364)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
>         at io.anuke.koru.desktop.DesktopLauncher.main(DesktopLauncher.java:23)
> 

Pls create automatic crash report.
I clone repository and run command gradle :desktop:run
Heh =(

**Comment by The28AWG** [comment]
Oh, sorry, its my video driver bug. Google says.

**Comment by The28AWG** [comment]
offensively...

**Comment by Anuken** [comment]
This might indeed be a driver bug, but I've changed some things in the problematic shader that could fix it.

As for error logs, there _is_ a system that creates error log files, but it only worked with errors in the update loop. I've fixed that now.

**Comment by The28AWG** [comment]
Console output:

> ../../../../src/intel/isl/isl.c:1370: FINISHME: validate row pitch of stencil surfaces
> java.lang.RuntimeException: Fragment shader:
> 0:2(12): warning: extension `GL_EXT_gpu_shader4' unsupported in fragment shader
> 0:18(15): error: no function with name 'textureSize2D'
> 0:22(20): warning: `size' used uninitialized
> 0:22(32): warning: `size' used uninitialized
> 
>         at io.anuke.ucore.graphics.Shader.<init>(Shader.java:14)
>         at io.anuke.ucore.core.Shaders.load(Shaders.java:17)
>         at io.anuke.koru.modules.Renderer.loadShaders(Renderer.java:96)
>         at io.anuke.koru.modules.Renderer.<init>(Renderer.java:72)
>         at io.anuke.koru.Koru.init(Koru.java:54)
>         at io.anuke.ucore.modules.ModuleController.create(ModuleController.java:98)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:364)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
>         at io.anuke.koru.desktop.DesktopLauncher.main(DesktopLauncher.java:23)
korulog-Sat Aug 05 18:43:27 EDT 2017.log:

> java.lang.RuntimeException: Fragment shader:
> 0(13) : warning C7555: 'varying' is deprecated, use 'in/out' instead
> 0(14) : warning C7555: 'varying' is deprecated, use 'in/out' instead
> 0(18) : error C7531: global function textureSize2D requires "#extension GL_EXT_gpu_shader4 : enable" before use
> 0(35) : warning C7533: global variable gl_FragColor is deprecated after version 120
> 
> io.anuke.ucore.graphics.Shader.<init>(Shader.java:14)
> io.anuke.ucore.core.Shaders.load(Shaders.java:17)
> io.anuke.koru.modules.Renderer.loadShaders(Renderer.java:96)
> io.anuke.koru.modules.Renderer.<init>(Renderer.java:72)
> io.anuke.koru.Koru.init(Koru.java:53)
> io.anuke.ucore.modules.ModuleController.create(ModuleController.java:98)
> com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
> com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:364)
> com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
> com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
> io.anuke.koru.desktop.DesktopLauncher.main(DesktopLauncher.java:23)

Need glxinfo log?

> the28awg@undefined:~/Development/Koru$ glxinfo 
> name of display: :1
> display: :1  screen: 0
> direct rendering: Yes
> server glx vendor string: SGI
> server glx version string: 1.4
> server glx extensions:
>     GLX_ARB_create_context, GLX_ARB_create_context_profile, 
>     GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
>     GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
>     GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
>     GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
>     GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
>     GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
>     GLX_OML_swap_method, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
>     GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group, GLX_SGI_swap_control
> client glx vendor string: Mesa Project and SGI
> client glx version string: 1.4
> client glx extensions:
>     GLX_ARB_create_context, GLX_ARB_create_context_profile, 
>     GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
>     GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
>     GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
>     GLX_EXT_create_context_es_profile, GLX_EXT_fbconfig_packed_float, 
>     GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, 
>     GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
>     GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
>     GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
>     GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
>     GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
>     GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
>     GLX_SGI_swap_control, GLX_SGI_video_sync
> GLX version: 1.4
> GLX extensions:
>     GLX_ARB_create_context, GLX_ARB_create_context_profile, 
>     GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
>     GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
>     GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
>     GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
>     GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
>     GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
>     GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
>     GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
>     GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
>     GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
>     GLX_SGI_swap_control, GLX_SGI_video_sync
> Extended renderer info (GLX_MESA_query_renderer):
>     Vendor: Intel Open Source Technology Center (0x8086)
>     Device: Mesa DRI Intel(R) Sandybridge Desktop  (0x102)
>     Version: 17.3.0
>     Accelerated: yes
>     Video memory: 1536MB
>     Unified memory: yes
>     Preferred profile: core (0x1)
>     Max core profile version: 3.3
>     Max compat profile version: 3.0
>     Max GLES1 profile version: 1.1
>     Max GLES[23] profile version: 3.0
> OpenGL vendor string: Intel Open Source Technology Center
> OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Desktop 
> OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.3.0-devel
> OpenGL core profile shading language version string: 3.30
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
>     GL_3DFX_texture_compression_FXT1, GL_AMD_draw_buffers_blend, 
>     GL_AMD_seamless_cubemap_per_texture, GL_AMD_shader_trinary_minmax, 
>     GL_AMD_vertex_shader_layer, GL_AMD_vertex_shader_viewport_index, 
>     GL_ANGLE_texture_compression_dxt3, GL_ANGLE_texture_compression_dxt5, 
>     GL_APPLE_object_purgeable, GL_ARB_ES2_compatibility, 
>     GL_ARB_ES3_compatibility, GL_ARB_arrays_of_arrays, GL_ARB_base_instance, 
>     GL_ARB_blend_func_extended, GL_ARB_buffer_storage, 
>     GL_ARB_clear_buffer_object, GL_ARB_clear_texture, GL_ARB_clip_control, 
>     GL_ARB_compressed_texture_pixel_storage, 
>     GL_ARB_conditional_render_inverted, GL_ARB_copy_buffer, GL_ARB_copy_image, 
>     GL_ARB_cull_distance, GL_ARB_debug_output, GL_ARB_depth_buffer_float, 
>     GL_ARB_depth_clamp, GL_ARB_direct_state_access, GL_ARB_draw_buffers, 
>     GL_ARB_draw_buffers_blend, GL_ARB_draw_elements_base_vertex, 
>     GL_ARB_draw_instanced, GL_ARB_enhanced_layouts, 
>     GL_ARB_explicit_attrib_location, GL_ARB_explicit_uniform_location, 
>     GL_ARB_fragment_coord_conventions, GL_ARB_fragment_layer_viewport, 
>     GL_ARB_fragment_shader, GL_ARB_framebuffer_object, 
>     GL_ARB_framebuffer_sRGB, GL_ARB_get_program_binary, 
>     GL_ARB_get_texture_sub_image, GL_ARB_half_float_pixel, 
>     GL_ARB_half_float_vertex, GL_ARB_instanced_arrays, 
>     GL_ARB_internalformat_query, GL_ARB_internalformat_query2, 
>     GL_ARB_invalidate_subdata, GL_ARB_map_buffer_alignment, 
>     GL_ARB_map_buffer_range, GL_ARB_multi_bind, GL_ARB_occlusion_query2, 
>     GL_ARB_pipeline_statistics_query, GL_ARB_pixel_buffer_object, 
>     GL_ARB_point_sprite, GL_ARB_program_interface_query, 
>     GL_ARB_provoking_vertex, GL_ARB_robustness, GL_ARB_sample_shading, 
>     GL_ARB_sampler_objects, GL_ARB_seamless_cube_map, 
>     GL_ARB_seamless_cubemap_per_texture, GL_ARB_separate_shader_objects, 
>     GL_ARB_shader_bit_encoding, GL_ARB_shader_draw_parameters, 
>     GL_ARB_shader_group_vote, GL_ARB_shader_objects, GL_ARB_shader_subroutine, 
>     GL_ARB_shader_texture_lod, GL_ARB_shader_viewport_layer_array, 
>     GL_ARB_shading_language_420pack, GL_ARB_shading_language_packing, 
>     GL_ARB_sync, GL_ARB_texture_barrier, GL_ARB_texture_buffer_object, 
>     GL_ARB_texture_buffer_object_rgb32, GL_ARB_texture_buffer_range, 
>     GL_ARB_texture_compression_rgtc, GL_ARB_texture_cube_map_array, 
>     GL_ARB_texture_float, GL_ARB_texture_gather, 
>     GL_ARB_texture_mirror_clamp_to_edge, GL_ARB_texture_multisample, 
>     GL_ARB_texture_non_power_of_two, GL_ARB_texture_query_levels, 
>     GL_ARB_texture_query_lod, GL_ARB_texture_rectangle, GL_ARB_texture_rg, 
>     GL_ARB_texture_rgb10_a2ui, GL_ARB_texture_storage, 
>     GL_ARB_texture_storage_multisample, GL_ARB_texture_swizzle, 
>     GL_ARB_timer_query, GL_ARB_transform_feedback2, 
>     GL_ARB_transform_feedback_overflow_query, GL_ARB_uniform_buffer_object, 
>     GL_ARB_vertex_array_bgra, GL_ARB_vertex_array_object, 
>     GL_ARB_vertex_attrib_binding, GL_ARB_vertex_shader, 
>     GL_ARB_vertex_type_10f_11f_11f_rev, GL_ARB_vertex_type_2_10_10_10_rev, 
>     GL_ARB_viewport_array, GL_ATI_blend_equation_separate, 
>     GL_ATI_texture_float, GL_EXT_abgr, GL_EXT_blend_equation_separate, 
>     GL_EXT_draw_buffers2, GL_EXT_draw_instanced, GL_EXT_framebuffer_blit, 
>     GL_EXT_framebuffer_multisample, GL_EXT_framebuffer_multisample_blit_scaled, 
>     GL_EXT_framebuffer_sRGB, GL_EXT_packed_depth_stencil, GL_EXT_packed_float, 
>     GL_EXT_pixel_buffer_object, GL_EXT_polygon_offset_clamp, 
>     GL_EXT_provoking_vertex, GL_EXT_shader_integer_mix, GL_EXT_texture_array, 
>     GL_EXT_texture_compression_dxt1, GL_EXT_texture_compression_rgtc, 
>     GL_EXT_texture_compression_s3tc, GL_EXT_texture_filter_anisotropic, 
>     GL_EXT_texture_integer, GL_EXT_texture_sRGB, GL_EXT_texture_sRGB_decode, 
>     GL_EXT_texture_shared_exponent, GL_EXT_texture_snorm, 
>     GL_EXT_texture_swizzle, GL_EXT_timer_query, GL_EXT_transform_feedback, 
>     GL_EXT_vertex_array_bgra, GL_IBM_multimode_draw_arrays, 
>     GL_INTEL_performance_query, GL_KHR_blend_equation_advanced, 
>     GL_KHR_context_flush_control, GL_KHR_debug, GL_KHR_no_error, 
>     GL_KHR_robustness, GL_MESA_pack_invert, GL_MESA_shader_integer_functions, 
>     GL_MESA_texture_signed_rgba, GL_NV_conditional_render, GL_NV_depth_clamp, 
>     GL_NV_packed_depth_stencil, GL_NV_texture_barrier, GL_OES_EGL_image, 
>     GL_S3_s3tc
> 
> OpenGL version string: 3.0 Mesa 17.3.0-devel
> OpenGL shading language version string: 1.30
> OpenGL context flags: (none)
> OpenGL extensions:
>     GL_3DFX_texture_compression_FXT1, GL_AMD_draw_buffers_blend, 
>     GL_AMD_seamless_cubemap_per_texture, GL_AMD_shader_trinary_minmax, 
>     GL_ANGLE_texture_compression_dxt3, GL_ANGLE_texture_compression_dxt5, 
>     GL_APPLE_object_purgeable, GL_APPLE_packed_pixels, 
>     GL_ARB_ES2_compatibility, GL_ARB_ES3_compatibility, 
>     GL_ARB_arrays_of_arrays, GL_ARB_blend_func_extended, 
>     GL_ARB_buffer_storage, GL_ARB_clear_buffer_object, GL_ARB_clear_texture, 
>     GL_ARB_clip_control, GL_ARB_color_buffer_float, 
>     GL_ARB_compressed_texture_pixel_storage, 
>     GL_ARB_conditional_render_inverted, GL_ARB_copy_buffer, GL_ARB_copy_image, 
>     GL_ARB_cull_distance, GL_ARB_debug_output, GL_ARB_depth_buffer_float, 
>     GL_ARB_depth_clamp, GL_ARB_depth_texture, GL_ARB_draw_buffers, 
>     GL_ARB_draw_buffers_blend, GL_ARB_draw_elements_base_vertex, 
>     GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location, 
>     GL_ARB_explicit_uniform_location, GL_ARB_fragment_coord_conventions, 
>     GL_ARB_fragment_program, GL_ARB_fragment_program_shadow, 
>     GL_ARB_fragment_shader, GL_ARB_framebuffer_object, 
>     GL_ARB_framebuffer_sRGB, GL_ARB_get_program_binary, 
>     GL_ARB_get_texture_sub_image, GL_ARB_half_float_pixel, 
>     GL_ARB_half_float_vertex, GL_ARB_instanced_arrays, 
>     GL_ARB_internalformat_query, GL_ARB_internalformat_query2, 
>     GL_ARB_invalidate_subdata, GL_ARB_map_buffer_alignment, 
>     GL_ARB_map_buffer_range, GL_ARB_multi_bind, GL_ARB_multisample, 
>     GL_ARB_multitexture, GL_ARB_occlusion_query, GL_ARB_occlusion_query2, 
>     GL_ARB_pipeline_statistics_query, GL_ARB_pixel_buffer_object, 
>     GL_ARB_point_parameters, GL_ARB_point_sprite, 
>     GL_ARB_program_interface_query, GL_ARB_provoking_vertex, 
>     GL_ARB_robustness, GL_ARB_sample_shading, GL_ARB_sampler_objects, 
>     GL_ARB_seamless_cube_map, GL_ARB_seamless_cubemap_per_texture, 
>     GL_ARB_separate_shader_objects, GL_ARB_shader_bit_encoding, 
>     GL_ARB_shader_draw_parameters, GL_ARB_shader_group_vote, 
>     GL_ARB_shader_objects, GL_ARB_shader_texture_lod, 
>     GL_ARB_shading_language_100, GL_ARB_shading_language_420pack, 
>     GL_ARB_shading_language_packing, GL_ARB_shadow, GL_ARB_sync, 
>     GL_ARB_texture_barrier, GL_ARB_texture_border_clamp, 
>     GL_ARB_texture_compression, GL_ARB_texture_compression_rgtc, 
>     GL_ARB_texture_cube_map, GL_ARB_texture_cube_map_array, 
>     GL_ARB_texture_env_add, GL_ARB_texture_env_combine, 
>     GL_ARB_texture_env_crossbar, GL_ARB_texture_env_dot3, 
>     GL_ARB_texture_float, GL_ARB_texture_gather, 
>     GL_ARB_texture_mirror_clamp_to_edge, GL_ARB_texture_mirrored_repeat, 
>     GL_ARB_texture_multisample, GL_ARB_texture_non_power_of_two, 
>     GL_ARB_texture_query_levels, GL_ARB_texture_query_lod, 
>     GL_ARB_texture_rectangle, GL_ARB_texture_rg, GL_ARB_texture_rgb10_a2ui, 
>     GL_ARB_texture_storage, GL_ARB_texture_storage_multisample, 
>     GL_ARB_texture_swizzle, GL_ARB_timer_query, GL_ARB_transform_feedback2, 
>     GL_ARB_transform_feedback_overflow_query, GL_ARB_transpose_matrix, 
>     GL_ARB_uniform_buffer_object, GL_ARB_vertex_array_bgra, 
>     GL_ARB_vertex_array_object, GL_ARB_vertex_attrib_binding, 
>     GL_ARB_vertex_buffer_object, GL_ARB_vertex_program, GL_ARB_vertex_shader, 
>     GL_ARB_vertex_type_10f_11f_11f_rev, GL_ARB_vertex_type_2_10_10_10_rev, 
>     GL_ARB_window_pos, GL_ATI_blend_equation_separate, GL_ATI_draw_buffers, 
>     GL_ATI_separate_stencil, GL_ATI_texture_env_combine3, 
>     GL_ATI_texture_float, GL_EXT_abgr, GL_EXT_bgra, GL_EXT_blend_color, 
>     GL_EXT_blend_equation_separate, GL_EXT_blend_func_separate, 
>     GL_EXT_blend_minmax, GL_EXT_blend_subtract, GL_EXT_compiled_vertex_array, 
>     GL_EXT_copy_texture, GL_EXT_draw_buffers2, GL_EXT_draw_instanced, 
>     GL_EXT_draw_range_elements, GL_EXT_fog_coord, GL_EXT_framebuffer_blit, 
>     GL_EXT_framebuffer_multisample, GL_EXT_framebuffer_multisample_blit_scaled, 
>     GL_EXT_framebuffer_object, GL_EXT_framebuffer_sRGB, 
>     GL_EXT_gpu_program_parameters, GL_EXT_multi_draw_arrays, 
>     GL_EXT_packed_depth_stencil, GL_EXT_packed_float, GL_EXT_packed_pixels, 
>     GL_EXT_pixel_buffer_object, GL_EXT_point_parameters, 
>     GL_EXT_polygon_offset, GL_EXT_polygon_offset_clamp, 
>     GL_EXT_provoking_vertex, GL_EXT_rescale_normal, GL_EXT_secondary_color, 
>     GL_EXT_separate_specular_color, GL_EXT_shader_integer_mix, 
>     GL_EXT_shadow_funcs, GL_EXT_stencil_two_side, GL_EXT_stencil_wrap, 
>     GL_EXT_subtexture, GL_EXT_texture, GL_EXT_texture3D, 
>     GL_EXT_texture_array, GL_EXT_texture_compression_dxt1, 
>     GL_EXT_texture_compression_rgtc, GL_EXT_texture_compression_s3tc, 
>     GL_EXT_texture_cube_map, GL_EXT_texture_edge_clamp, 
>     GL_EXT_texture_env_add, GL_EXT_texture_env_combine, 
>     GL_EXT_texture_env_dot3, GL_EXT_texture_filter_anisotropic, 
>     GL_EXT_texture_integer, GL_EXT_texture_lod_bias, GL_EXT_texture_object, 
>     GL_EXT_texture_rectangle, GL_EXT_texture_sRGB, GL_EXT_texture_sRGB_decode, 
>     GL_EXT_texture_shared_exponent, GL_EXT_texture_snorm, 
>     GL_EXT_texture_swizzle, GL_EXT_timer_query, GL_EXT_transform_feedback, 
>     GL_EXT_vertex_array, GL_EXT_vertex_array_bgra, 
>     GL_IBM_multimode_draw_arrays, GL_IBM_rasterpos_clip, 
>     GL_IBM_texture_mirrored_repeat, GL_INGR_blend_func_separate, 
>     GL_INTEL_performance_query, GL_KHR_blend_equation_advanced, 
>     GL_KHR_context_flush_control, GL_KHR_debug, GL_KHR_no_error, 
>     GL_KHR_robustness, GL_MESA_pack_invert, GL_MESA_shader_integer_functions, 
>     GL_MESA_texture_signed_rgba, GL_MESA_window_pos, GL_NV_blend_square, 
>     GL_NV_conditional_render, GL_NV_depth_clamp, GL_NV_light_max_exponent, 
>     GL_NV_packed_depth_stencil, GL_NV_primitive_restart, 
>     GL_NV_texgen_reflection, GL_NV_texture_barrier, 
>     GL_NV_texture_env_combine4, GL_NV_texture_rectangle, GL_OES_EGL_image, 
>     GL_OES_read_format, GL_S3_s3tc, GL_SGIS_generate_mipmap, 
>     GL_SGIS_texture_border_clamp, GL_SGIS_texture_edge_clamp, 
>     GL_SGIS_texture_lod, GL_SUN_multi_draw_arrays
> 
> OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.3.0-devel
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
> OpenGL ES profile extensions:
>     GL_ANGLE_texture_compression_dxt3, GL_ANGLE_texture_compression_dxt5, 
>     GL_APPLE_texture_max_level, GL_EXT_blend_func_extended, 
>     GL_EXT_blend_minmax, GL_EXT_clip_cull_distance, GL_EXT_color_buffer_float, 
>     GL_EXT_compressed_ETC1_RGB8_sub_texture, GL_EXT_discard_framebuffer, 
>     GL_EXT_draw_buffers, GL_EXT_draw_buffers_indexed, 
>     GL_EXT_draw_elements_base_vertex, GL_EXT_frag_depth, 
>     GL_EXT_map_buffer_range, GL_EXT_multi_draw_arrays, 
>     GL_EXT_polygon_offset_clamp, GL_EXT_read_format_bgra, GL_EXT_robustness, 
>     GL_EXT_separate_shader_objects, GL_EXT_shader_integer_mix, 
>     GL_EXT_texture_border_clamp, GL_EXT_texture_compression_dxt1, 
>     GL_EXT_texture_filter_anisotropic, GL_EXT_texture_format_BGRA8888, 
>     GL_EXT_texture_rg, GL_EXT_texture_sRGB_decode, 
>     GL_EXT_texture_type_2_10_10_10_REV, GL_EXT_unpack_subimage, 
>     GL_INTEL_performance_query, GL_KHR_blend_equation_advanced, 
>     GL_KHR_context_flush_control, GL_KHR_debug, GL_KHR_no_error, 
>     GL_KHR_robustness, GL_MESA_shader_integer_functions, GL_NV_draw_buffers, 
>     GL_NV_fbo_color_attachments, GL_NV_read_buffer, GL_NV_read_depth, 
>     GL_NV_read_depth_stencil, GL_NV_read_stencil, GL_OES_EGL_image, 
>     GL_OES_EGL_image_external, GL_OES_EGL_sync, 
>     GL_OES_compressed_ETC1_RGB8_texture, GL_OES_depth24, GL_OES_depth_texture, 
>     GL_OES_depth_texture_cube_map, GL_OES_draw_buffers_indexed, 
>     GL_OES_draw_elements_base_vertex, GL_OES_element_index_uint, 
>     GL_OES_fbo_render_mipmap, GL_OES_get_program_binary, GL_OES_mapbuffer, 
>     GL_OES_packed_depth_stencil, GL_OES_rgb8_rgba8, GL_OES_sample_shading, 
>     GL_OES_sample_variables, GL_OES_shader_multisample_interpolation, 
>     GL_OES_standard_derivatives, GL_OES_stencil8, GL_OES_surfaceless_context, 
>     GL_OES_texture_3D, GL_OES_texture_border_clamp, GL_OES_texture_float, 
>     GL_OES_texture_float_linear, GL_OES_texture_half_float, 
>     GL_OES_texture_half_float_linear, GL_OES_texture_npot, 
>     GL_OES_vertex_array_object, GL_OES_vertex_half_float

Really no GL_EXT_gpu_shader4 extension. =(
Can you suggest a solution?

**Comment by The28AWG** [comment]
https://askubuntu.com/questions/810433/opengl-extension-gl-ext-gpu-shader4
https://stackoverflow.com/questions/16849001/enabling-opengl-extensions
Huh. Magic!
Extension not need?

**Comment by The28AWG** [comment]
I fix it!
replace textureSize2D in textureSize and add #version 130 if need

**Comment by Anuken** [comment]
Hmmm... After looking through the code, I realized I don't need textureSize2D/textureSize at all. It should work without them now.
